services:
  - type: web
    name: ubaidfastfoodz-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && npx tsx prisma/seed.ts && npx tsx src/index.ts
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
