/** Karachi towns & neighbourhoods — seeded once; admin toggles delivery + charges. */
export const KARACHI_AREAS = [
  "Abbottabad Colony",
  "Ahsanabad",
  "Airport Area",
  "Akhtar Colony",
  "Al-Hilal Society",
  "Askari 1",
  "Askari 2",
  "Askari 3",
  "Askari 4",
  "Askari 5",
  "Azam Basti",
  "Azam Town",
  "Baldia Town",
  "Bahadurabad",
  "Bahria Town Karachi",
  "Banaras Colony",
  "Bhimpura",
  "Boat Basin",
  "Buffer Zone",
  "Baldia",
  "Cantonment",
  "Chakra Goth",
  "Clifton Block 1",
  "Clifton Block 2",
  "Clifton Block 3",
  "Clifton Block 4",
  "Clifton Block 5",
  "Clifton Block 6",
  "Clifton Block 7",
  "Clifton Block 8",
  "Clifton Block 9",
  "DHA Phase 1",
  "DHA Phase 2",
  "DHA Phase 4",
  "DHA Phase 5",
  "DHA Phase 6",
  "DHA Phase 7",
  "DHA Phase 8",
  "Defence View Housing Society",
  "Drigh Road",
  "Esso Nagri",
  "FB Area Block 10",
  "FB Area Block 11",
  "FB Area Block 12",
  "FB Area Block 13",
  "FB Area Block 14",
  "FB Area Block 15",
  "FB Area Block 16",
  "FB Area Block 17",
  "FB Area Block 18",
  "FB Area Block 19",
  "FB Area Block 20",
  "FB Area Block 21",
  "Faisal Cantonment",
  "Gadap Town",
  "Garden East",
  "Garden West",
  "Gizri",
  "Golimar",
  "Gulberg",
  "Gulistan-e-Jauhar Block 1",
  "Gulistan-e-Jauhar Block 2",
  "Gulistan-e-Jauhar Block 3",
  "Gulistan-e-Jauhar Block 4",
  "Gulistan-e-Jauhar Block 5",
  "Gulistan-e-Jauhar Block 6",
  "Gulistan-e-Jauhar Block 7",
  "Gulistan-e-Jauhar Block 8",
  "Gulistan-e-Jauhar Block 9",
  "Gulistan-e-Jauhar Block 10",
  "Gulistan-e-Jauhar Block 11",
  "Gulistan-e-Jauhar Block 12",
  "Gulistan-e-Jauhar Block 13",
  "Gulistan-e-Jauhar Block 14",
  "Gulistan-e-Jauhar Block 15",
  "Gulistan-e-Jauhar Block 16",
  "Gulistan-e-Jauhar Block 17",
  "Gulistan-e-Jauhar Block 18",
  "Gulistan-e-Jauhar Block 19",
  "Gulistan-e-Jauhar Block 20",
  "Gulshan-e-Iqbal Block 1",
  "Gulshan-e-Iqbal Block 2",
  "Gulshan-e-Iqbal Block 3",
  "Gulshan-e-Iqbal Block 4",
  "Gulshan-e-Iqbal Block 5",
  "Gulshan-e-Iqbal Block 6",
  "Gulshan-e-Iqbal Block 7",
  "Gulshan-e-Iqbal Block 8",
  "Gulshan-e-Iqbal Block 9",
  "Gulshan-e-Iqbal Block 10",
  "Gulshan-e-Iqbal Block 11",
  "Gulshan-e-Iqbal Block 12",
  "Gulshan-e-Iqbal Block 13",
  "Gulshan-e-Iqbal Block 14",
  "Gulshan-e-Iqbal Block 15",
  "Gulshan-e-Iqbal Block 16",
  "Gulshan-e-Iqbal Block 17",
  "Gulshan-e-Iqbal Block 18",
  "Gulshan-e-Iqbal Block 19",
  "Gulshan-e-Iqbal Block 20",
  "Gulshan-e-Maymar",
  "Hawks Bay",
  "Hussainabad",
  "Ibrahim Hyderi",
  "Ittehad Town",
  "Jamshed Quarters",
  "Jamshed Town",
  "Jinnah Colony",
  "Johar Mor",
  "KDA Scheme 1",
  "Kemari",
  "Korangi",
  "Korangi Creek",
  "Korangi Industrial Area",
  "Landhi",
  "Liaquatabad",
  "Lyari",
  "Malir",
  "Malir Cantonment",
  "Malir City",
  "Manora",
  "Mauripur",
  "Mehran Town",
  "Metroville",
  "Moinabad",
  "Mominabad",
  "Nagan Chowrangi",
  "Napier Quarter",
  "Nazimabad Block 1",
  "Nazimabad Block 2",
  "Nazimabad Block 3",
  "Nazimabad Block 4",
  "Nazimabad Block 5",
  "New Karachi Sector 5",
  "New Karachi Sector 11",
  "New Karachi Sector 15",
  "North Karachi Sector 11",
  "North Karachi Sector 15",
  "North Nazimabad Block A",
  "North Nazimabad Block B",
  "North Nazimabad Block C",
  "North Nazimabad Block D",
  "North Nazimabad Block E",
  "North Nazimabad Block F",
  "North Nazimabad Block G",
  "North Nazimabad Block H",
  "North Nazimabad Block I",
  "North Nazimabad Block J",
  "North Nazimabad Block K",
  "North Nazimabad Block L",
  "North Nazimabad Block M",
  "North Nazimabad Block N",
  "Orangi Town Sector 1",
  "Orangi Town Sector 2",
  "Orangi Town Sector 3",
  "Orangi Town Sector 4",
  "Orangi Town Sector 5",
  "Orangi Town Sector 6",
  "Orangi Town Sector 7",
  "Orangi Town Sector 8",
  "Orangi Town Sector 9",
  "Orangi Town Sector 10",
  "Orangi Town Sector 11",
  "PECHS Block 1",
  "PECHS Block 2",
  "PECHS Block 3",
  "PECHS Block 6",
  "PIB Colony",
  "Pipri",
  "Quaidabad",
  "Saddar",
  "Safoora Goth",
  "Scheme 33 Sector 1",
  "Scheme 33 Sector 2",
  "Scheme 33 Sector 3",
  "Scheme 33 Sector 4",
  "Scheme 33 Sector 5",
  "Shah Faisal Colony 1",
  "Shah Faisal Colony 2",
  "Shah Faisal Colony 3",
  "Shah Latif Town",
  "Sharfabad",
  "Sher Shah",
  "SITE Area",
  "Soldier Bazaar",
  "Surjani Town Sector 1",
  "Surjani Town Sector 2",
  "Surjani Town Sector 3",
  "Surjani Town Sector 4",
  "Surjani Town Sector 5",
  "Surjani Town Sector 6",
  "Surjani Town Sector 7",
  "Tariq Road",
  "Tipu Sultan Road",
  "University Road",
  "Water Pump",
  "West Wharf",
] as const;

/** Areas enabled for delivery on first seed (admin can change later). */
export const DEFAULT_DELIVERING_AREAS = new Set([
  "Clifton Block 2",
  "Clifton Block 5",
  "DHA Phase 5",
  "DHA Phase 6",
  "PECHS Block 2",
  "Gulshan-e-Iqbal Block 13",
  "North Nazimabad Block H",
  "Bahria Town Karachi",
  "Malir Cantonment",
  "Boat Basin",
  "Saddar",
  "Gulistan-e-Jauhar Block 10",
  "Shah Faisal Colony 1",
  "Tariq Road",
  "Defence View Housing Society",
]);

export function defaultChargeForArea(name: string) {
  if (name.includes("DHA") || name.includes("Clifton") || name.includes("Defence")) return 200;
  if (name.includes("Bahria")) return 250;
  if (name.includes("Malir") || name.includes("Landhi") || name.includes("Korangi")) return 180;
  return 150;
}
